export const CUSTOMER_ROUTES = {
  root: "/customer",
  home: "/customer/home",
  dashboard: "/customer/dashboard",
  shop: "/customer/shop",
  tryOn: "/customer/try-on",
  tryOnHistory: "/customer/try-on/history",
  tryOnProduct: (productId: string) => `/customer/try-on/${productId}`,
  favorites: "/customer/favorites",
  account: "/customer/account",
  addresses: "/customer/account/addresses",
  avatar: "/customer/avatar",
  avatarManual: "/customer/avatar/manual",
  avatarPhoto: "/customer/avatar/photo",
  productDetails: (productId: string) => `/customer/products/${productId}`,
  cart: "/customer/cart",
  checkout: "/customer/checkout",
  outfits: "/customer/outfits",
  aiSuggestions: "/customer/ai-suggestions",
  wardrobeCollections: "/customer/wardrobe/collections",
  compare: "/customer/compare",
  about: "/customer/about",
  shippingReturns: "/customer/shipping-returns",
  blog: "/customer/blog",
  login: "/login/customer",
  signup: "/signup/customer",
  forgotPassword: "/forgot-password/customer",
  resetPassword: "/reset-password/customer",
} as const;

export type CustomerRouteKey = keyof typeof CUSTOMER_ROUTES;
export type CustomerRoutePath = (typeof CUSTOMER_ROUTES)[CustomerRouteKey];
